### PR TITLE
Fix Schedule Insert (Strict Mode)

### PR DESCRIPTION
**Pull request by FatihKoz**
Database and Schedule Class fixes to allow adding schedules when Strict Mode is enabled at database level and can not be closed/disabled

If install is already completed, below queries will change the table structure as needed
```sql
ALTER TABLE phpvms_schedules CHANGE route route NULL DEFAULT NULL;
ALTER TABLE phpvms_schedules CHANGE route_details route_details NULL DEFAULT NULL;
ALTER TABLE phpvms_schedules CHANGE flightlevel flightlevel NULL DEFAULT NULL;
ALTER TABLE phpvms_schedules CHANGE price price NULL DEFAULT NULL;
ALTER TABLE phpvms_schedules CHANGE notes notes NULL DEFAULT NULL;
```

### CODE REVIEW

**Comment by FatihKoz** [comment]
Up to my understanding dep/arr times are mandatory for v5, this is why I did not changed anything about them.

**Comment by FatihKoz** [comment]
Just for your info, doing/testing these changes with;

- apache 2.4.51
- php 7.4.27
- maria 10.6.5

So I expect them to work with earlier versions too (like php7.3 and maria 10.5 etc)

**Comment by ProAviaAZ** [comment]
"Up to my understanding dep/arr times are mandatory for v5, this is why I did not changed anything about them."

It didn't used to need anything there prior to MySQL 5.7.5 or MariaDB 10.2 - I have been using just a blank space if entering schedules manually if a dep/arr time isn't needed (since host updated MySQL to 5.7.34). I have found almost every entry in the manual schedules input now requires some type of entry. I believe the Route field somehow automatically added a 'space' character every time the schedule is edited also. No idea why or how.

Maybe adding a default entry into the install SQL for this might be appropriate?
I am open to any and all ideas/suggestions to get this working correctly.

**Comment by FatihKoz** [comment]
Looks like it is a side effect of Strict Mode then, I think we can fix those fields too. 

Technically speaking, on database side `NOT NULL DEFAULT ''` is not logical at all, you are saying the db engine to have an entry there (NOT NULL) but then force the default to an empty string (DEFAULT ''), which is basically NULL.

And this causes problems, if it should be empty or say "can be" empty according to the code you have to read/process that record then it should be reflected at database level too.

Looks like this is the main problem v5.x has at the moment, specially when STRICT MODE is enabled it stops working just because of this. There are no defaults defined at database level for some fields and they are not allowed to be null, yet  the code tries to send empty strings which is not possible with strict mode.

So, up to my understanding, the solution has two steps;

1. Check the code, reduce/remove empty strings from queries wherever used and possible
2. Check the database, implement proper null acceptance and defaults (if the field is really nullable, like route or flight level, not mandatory for operational usage)

Anyway, I am pretty much used to v7 and it's logic and have no experience with v5. Specially how it worked before strict mode so I am just guessing about fields :)

Hope it works

**Pull request closed without merging**
